version: '3.3'

services:
    jenkins:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: jenkins-serv
        ports:
            - "50000:50000"
            - "8080:8080"
        volumes:
          - Jenkins_home:/var/jenkins_home
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/snap/docker/Current:/usr/bin/docker
volumes:
    Jenkins_home: